language: node_js
node_js:
<<<<<<< HEAD
  - "0.12"

branches:
  except:
    - gh-pages

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - npm install -g bower grunt-cli
  - bower install

script: "grunt --verbose"

git:
  depth: 10
=======
  - 0.10

env: BROWSERS=firefox E2E_BROWSERS=Firefox

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver

script:
  - scripts/private/test-all.sh
>>>>>>> e451776a238fce25e35aa45daf50f4e8993eed8a
